### ISSUE TITLE
FAPI Locker - redesign

### ISSUE THREAD

**Issue by slischka** [fapi-cz/fapi-locker#6]
**Nastavení FAPI Lockeru ve WP**

- [x] Propojení s účtem FAPI realizovat pomocí API klíče, nikoli uživatelského jména a hesla.
- [x] změny textů:
- nadpis: Locker: Nastavení FAPI údajů -> Nastavení rozšíření FAPI Locker
- nadpisy sekcí:
Nastavení údajů -> Přístup do FAPI
Nastavení vzhledu -> Vzhled

**Nastavení zamčení stránky pomocí FAPI Lockeru ve WP**

- [x] Zapínání/vypínání FAPI Lockeru udělat jako přepínač (šoupátko).
- [x] Tlačítko pro odemčení stránky bych změnil pouze na textový odkaz, který nebude tak dominantní jako tlačítko pro zakoupení přístupu.
- [x] Přidat možnost nastavení textu odkazu pro odemčení obsahu (zadání přístupové e-mailové adresy).
- popisek pole: Text odkazu pro odemčení obsahu
- [x] V nastavení zamčení stránky sloučit (a seřadit v tomto pořadí):
1) volby, které se týkají toho, co se uživateli zobrazuje na zamčené stránce (vysvětlující text, text odkazu pro odemčení, text tlačítka pro zakoupení přístupu)
2) nastavení pro zakoupení přístupu (volba prodejního formuláře a prodejní položky)
3) nastavení pro "generální" přístup (e-mailové adresy pro přístup i bez zakoupení produktu)
- [x] změny textů:
- název bloku: Locker -> FAPI Locker
- Stav lockeru -> Stav
- Text v případě nezakoupení článku -> Obsah zobrazený před udělením přístupu
- Text tlačítka pro zobrazení Prodejního formuláře -> Text tlačítka pro zobrazení prodejního formuláře
- Název položky na faktuře -> Produkt udělující přístup k obsahu
- Přidat další položku -> Přidat další produkt
- Zvolte Prodejní formulář FAPI -> Prodejní formulář pro zakoupení přístupu
- Povolené e-maily -> E-mailové adresy s univerzálním přístupem
- Při zadávání více emailů je oddělujte čárkou. -> Adresy oddělujte čárkou.
- Globální nastavení barvy a ohraničení prodejního formuláře -> Nastavení vzhledu FAPI Lockeru

**Použití FAPI Lockeru**

- [x] Aktuálně se mi při testování vůbec nedaří odemknout přístup ke stránce po zadání e-mailové adresy, se kterou jsem si koupil přístup ve FAPI (v MW 2.0)
- [x] V MW 3.0 pro změnu FAPI Locker stránku vůbec nezamyká.
- [x] Neresponzivní formulář se na stránce s FAPI Lockerem zarovnává vlevo, což neodpovídá zarovnání ostatních prvků FAPI Lockeru. -> Vycentrovat formulář FAPI na stánce.

**Technologie**
- [x] Použít nového FAPI php clienta a zbavit se starého
- [ ] Kód napsat pro php 7.1+. PHP client na něm běží většina dnešních webu na MW jedou taky na php 7.1+
- [x] Doplnit někam do WP kontrolu aby plugin nešel nainstalovat pokud klient nebude mít php 7.1+

-----

Nice to have:
- Přístup návštěvníka k zamčené stránce by bylo fajn udělat přes jiný údaj než přes e-mailovou adresu (ideální by byl nějaký vygenerovaný unikátní přístupový kód, ale k tomu FAPI momentálně není přizpůsobené).
- Umožnit nastavení všech viditelných textů, např. popisku pole pro zadání přístupového údaje ("Zadejte e-mail"), tlačítka pro odemknutí ("Odemknout") apod. FAPI Locker by tak bylo možné snadno nastavit do libovolného jazyka (kromě všech chybových hlášek, kterých je tam docela dost a uživatel je určitě nastavovat nebude).
- Umožnit nastavit velikost písma a styl tlačítek (zakulacení rohů, stín apod.). Teď je možné nastavit pouze barvu textu a pozadí a navíc "tlačítka" nejsou ve skutečnosti tlačítka, ale jen podbarvené podtržené odkazy, což nevypadá dobře.

Související úpravy ve FAPI:
- Při použití responzivní šablony formuláře FAPI se formulář zobrazí na plnou šířku stránky, což vypadá děsně.
- Obsah uvnitř prodejního formuláře FAPI se zobrazuje vycentrovaný, přestože se tak zobrazovat nemá (produkty, způsoby platby, texty apod.).

origin: https://github.com/smartemailing/fapi/issues/2739#issue-482928445

**Comment by slischka** [comment]
- [ ] vytvořit branch v3.0

**Comment by radimtopic** [comment]
- [ ] možnost odstranit tlačítko pro zakoupení přístupu (když už není v prodeji): Má představa je taková, že by v nastavení zamčení stránky (nad nastavením textu tlačítka pro zakoupení přístupu) přibyl checkbox "Zobrazit tlačítko pro zakoupení přístupu". Checkbox by byl defaultně zaškrtnutý. Pokud ho uživatel odškrtne, zmizí nastavení textu tlačítka pro zakoupení přístupu (v takovém stavu nedává smysl).
- [ ] automaticky ověřovat funkčnost připojení k FAPI: Když se zadají přístupové údaje k FAPI v nastavení FAPI Lockeru a při zobrazení stránky s nastavením FAPI Lockeru ve WP ověřit, zda je propojení s FAPI funkční, a pod přístupovými údaji na stránce vypsat stav (např. "Připojeno", nebo "Nepřipojeno").

Nice to have:
- [ ] přidat “generální” přístup na všechny stránky zamčené FAPI Lockerem: Pokud by to nebylo moc náročné, dalo by se do centrálního nastavení FAPI Lockeru přidat pole pro zadání e-mailových adres s "generálním" přístupem? Zadaná e-mailová adresa by měla přístup ke všem zamčeným stránkám na daném webu (bez nutnosti ji přidávat do nastavení každé stránky zvlášť.

**Comment by radimtopic** [comment]
Otestoval jsem FAPI Locker v. 2.4 na svém webu, konkrétně na stránce http://radim.mioweb.cz/locker/ (MW 3.0).

- [ ] Nedaří se mi odemkout zamčenou stránku. Když na zamčené stránce zadám adresu, na kterou byl produkt odemykající stránku v nastavení FAPI Lockeru zakoupen (f20test@seznam.cz), zobrazí se mi tato hláška: 
Pro e-mail "f20test@seznam.cz" neevidujeme žádnou objednávku ani platbu (kód 003 - neznámý email).
Je emailová adresa správná?
(Odemčení stránky funguje jen pro e-mailové adresy zadané v nastavení - "E-mailové adresy s univerzálním přístupem")
- [ ] Chybové hlášky se zobrazují na zamčené stránce vlevo od ovládání FAPI Lockeru a zůstávají trvale zobrazeny. Když pak kliknu na tlačítko pro zakoupení přístupu (zobrazí se prodejní formulář), je formulář odsazen zleva o prostor, který zabírá zobrazená hláška.

![locker1](https://user-images.githubusercontent.com/10176552/68094520-b0bee100-fea1-11e9-9ca4-12e5002d0285.png)

- [ ] Když se zobrazí prodejní formulář, měl by odkaz pro odemčení stránky ("Mám koupeno, chci odemknout obsah.") zmizet.
- [ ] Nefunguje nastavení barvy pozadí a textu tlačítka. (Po nastavení barev a uložení nastavení se tlačítko stále zobrazuje v defaultní podobě.)
- [ ] Nešlo by text odkazu pro odemčení obsahu nastavovat přímo u zamykané stránky? Teď je to trochu nelogicky v globálním nastavení FAPI Lockeru, přitom všechny další texty se nastavují u zamykané stránky. Je to výhodné např. i pro nastavení různých stránek v různém jazyce.
- [ ] Prvky nastavení zamykané stránky zobrazit v tomto pořadí:
- šoupátko pro aktivaci FAPI Lockeru (nový popisek: "Zamknout stránku")
- Text zobrazený před udělením přístupu
- Text odkazu pro odemčení obsahu
- Produkt udělující přístup k obsahu
- šoupátko "Zobrazit tlačítko pro zakoupení obsahu"
- Text tlačítka pro zobrazení prodejního formuláře
- Prodejní formulář pro zakoupení přístupu
- E-mailové adresy s univerzálním přístupem
- [ ] Název celého bloku s nastavením zamykání stránky změnit z "Locker" na "FAPI Locker".
- [ ] Změnit nadpis nad šoupátkem aktivujícím FAPI Locker: Stav -> Zamknout stránku
- [ ] Když přejdu na nastavení vzhledu přes odkaz "Nastavení vzhledu FAPI Lockeru" (z nastavení zamykané stránky), je v URL jedno lomítko navíc, např. http://radim.mioweb.cz/wp-admin//options-general.php?page=fapi-locker místo http://radim.mioweb.cz/wp-admin/options-general.php?page=fapi-locker
- [ ] Změnit popisek pole v nastavení stránky: Obsah zobrazený před udělením přístupu -> Text zobrazený před udělením přístupu
- [ ] Sjednotit velikost písma - texty tlačítek zvětšit na velikost ostatních textů.
- [ ] Při zadání e-mailové adresy, která odemyká přístup ke stránce se zobrazuje text: "Zadejte kód pro odemčení:" Z toho není jasné, že uživatel má zadat svou e-mailovou adresu. Bylo by dobré, kdyby ten text i text tlačítka (v současné době "Odemknout") šel uživatelsky nastavit v nastavení zamykané stránky.
- [ ] Bylo by fajn sjednotit formát zadávání e-mailových adres s univerzálním přístupem (v globálním nastavení se zadávají na samostatné řádky a v nastavení zamykané stránky se oddělují čárkou).

**Comment by radimtopic** [comment]
Ještě pár kosmetických úprav...

V přehledu pluginů ve WP je jakási anotace pluginu a je tam uvedeno:
	
>Zamykání článků a stránek s ověřováním uhrazené platby přes FAPI s možností přímého nákupu.
>Verze 2.3 | Autor: Firma 2.0 - FAPI | Navštívit web pluginu

Změnil bych to následovně:

Zamykání stránek a článků s možností zakoupení přístupu přes prodejní aplikaci FAPI.
Verze <aktuální verze> | Autor: FAPI Business s.r.o. | Navštívit web pluginu

**Comment by kotmic** [comment]
> Ještě pár kosmetických úprav...
> 
> V přehledu pluginů ve WP je jakási anotace pluginu a je tam uvedeno:
> 
> > Zamykání článků a stránek s ověřováním uhrazené platby přes FAPI s možností přímého nákupu.
> > Verze 2.3 | Autor: Firma 2.0 - FAPI | Navštívit web pluginu
> 
> Změnil bych to následovně:
> 
> Zamykání stránek a článků s možností zakoupení přístupu přes prodejní aplikaci FAPI.
> Verze <aktuální verze> | Autor: FAPI Business s.r.o. | Navštívit web pluginu

Jj, toto uz je nove upravene, jen ti vidis tu starou verzi, co nejde z toho MW vymazat :)

**Comment by radimtopic** [comment]
Jasně, já jen, že ten úpravu toho textu jsem v těch původních připomínkách neměl. Tak to prosím ještě zreviduj.

Nevím, co bývá zvykem psát jako autora. Buď tam uveďme oficiální název firmy, nebo - pokud by to mělo být méně formální - postačí asi i "FAPI".

**Comment by radimtopic** [comment]
Funkční chyby:
- [ ] nedaří se mi odemknout obsah na stránce http://locker.happypaws.cz/zamcena-stranka/ při zadání adresy f20test@seznam.cz (např. objednávka 202010507)

Kosmetické úpravy:
- [ ] změnit text v popisu pluginu na: "Zamykání stránek a článků s možností zakoupení přístupu přes prodejní aplikaci FAPI."
- [ ] při funkčním propojení s FAPI se zobrazuje: "Stav přípojení: připojeno", změnit na "Stav propojení: připojeno"
- [ ] v nastavení pluginu změnit nadpis "Přístup do FAPI" na "Propojení s FAPI"
- [ ] v nastavení pluginu změnit nadpis "Nastavení vzhledu" na "Vzhled"
- [ ] do nastavení pluginu přidat nadpis (nad pole pro vyplnění e-mailových adres): "Přístup k obsahu"
- [ ] v nastavení zamčené stránky chybí nastavení textu odkazu pro odemčení obsahu
- [ ] změnit popisek (v nastavení zamčené stránky): "Zobrazit tlačítko pro zakoupení obsahu" -> "Zobrazit tlačítko pro zakoupení přístupu"
- [ ] změnit text pod polem pro zadání adres s univerzálním přístupem v nastavení pluginu na text: "Adresy oddělujte čárkou." (aby byl jednotný text v nastavení pluginu a v nastavení stránky)
- [ ] sjednotit psaní "e-mail", "e-mailová adresa" apod. v chybových hláškách na verzi se spojovníkem (např. u hlášky: "Pro e-mail ... neevidujeme žádnou objednávku ani platbu (kód 003 - neznámý email). Je emailová adresa správná?")

Z popisků mám docela zmatek v tom, co se myslí tím "globálním" nebo "univerzálním" přístupem (v nastavení stránky je to teď popsáno špatně). Bylo by dobré vhodným pojmenováním nějak jasně odlišit univerzální přístup v rámci celého webu a v rámci jedné zamčené stránky. Navrhuji tyto popisky:
- v nastavení pluginu: "E-mailové adresy s univerzálním přístupem (pro všechny zamčené stránky)"
- v nastavení stránky: "E-mailové adresy s univerzálním přístupem (pro tuto stránku)"

**Comment by kotmic** [comment]
Změny nasazeny, možno otestovat znovu na http://locker.happypaws.cz.

Jinak se omlouvám za to, jak nefungovalo to odemčení. Bylo to způsobené tím, že FAPI Locker z historických důvodů našel klienta dle e-mailu a pro něj hledal zaplacené faktury. Problém nastal ve chvíli, kdy klientů pod stejným e-mailem bylo víc. Toto už je nyní ošetřeno a i když pro f20test@seznam.cz existuje více klientů, hledá to zaplacené faktury ve všech klientech, které mají přiřazený tento e-mail.

Možno tedy otestovat znovu a snad už to bude ok. Textace jsem upravil a přidal do nastavení FAPI lockeru na konkrétní stránce možnost upravit popisek odkazu pro odemčení obsahu

**Comment by radimtopic** [comment]
@kotmic Super, myslím, že už se to blíží... 👍 Ještě jsem tam ale našel pár věcí... (něco z toho jsem psal už dřív)

Funkční věci:
- [ ] Když je k faktuře vystaven opravný daňový doklad (ODD), zůstává původní objednávka zaplacená, ale fakticky je ve FAPI zrušena (zmizí i z nástěnky a ve statistikách se objeví jako stornovaná). Toto je potřeba zohlednit i u zakoupeného přístupu v rámci FAPI Lockeru. Když je k objednávce vystaven ODD, měl by se FAPI Locker chovat, jako by objednávka nebyla zaplacena. (Viz objednávka 202040004 v mém účtu radim@fapi.cz.)
- [ ] Nejde mi zrušit zobrazení tlačítka pro zakoupení přístupu. Když vypnu volbu "Zobrazit tlačítko pro zakoupení přístupu" a stránku uložím, při následném otevření nastavení stránky je volba stále zapnutá (a na stránce tlačítko taky nezmizí).

Nastavení pluginu:
- [ ] Stav propojení (připojeno/nepřipojeno) dát až na konec části "Propojení s FAPI", pod API klíč. Tam to podle mě patří nejlíp. (Sorry, že jsem si toho nevšiml dřív. ;-)

Nastavení stránky:
- [ ] Nastavení tlačítka pro zobrazení prodejního formuláře ("Text tlačítka pro zobrazení prodejního formuláře" + příslušné pole) zobrazovat jen tehdy, když je přepínač "Zobrazit tlačítko pro zakoupení přístupu" aktivní. V opačném případě to skrýt.
- [ ] Volba "Zobrazit tlačítko pro zakoupení přístupu" by při založení nové stránky a nastavování FAPI Lockeru měla být ve výchozím stavu aktivní.

Zamčená stránka/odemykání stránky:
- [ ] Změnit text: "Zadejte e-mailovou adresu, kterou jste použili v objednávce:" -> "Zadejte e-mailovou adresu, kterou jste použili v objednávce." (na konci tečka místo dvojtečky)
- [ ] Slova "e-mail", "e-mailová adresa" apod. v chybových hláškách uvádět se spojovníkem (např. u hlášky: "Pro e-mailovou adresu ... neevidujeme žádnou objednávku ani platbu (kód 003 - neznámý email). Je emailová adresa správná?").

**Comment by kotmic** [comment]
Ahoj, zaimplementoval jsem všechny poznatky, které jsi k tomu měl a myslím, že jsem si dostatečně pohrál s těmi opravnými doklady. Trvalo mi to celkem dlouho, ale nemohli jsme to pustit ven polo funkční, takže aktuálně to pružně reaguje na veškeré opravné doklady na faktury, zkoušel jsem různé scénáře.

1. scénář - pro zobrazení stránky je vyžadováno zboží A
a) koupím si zboží A -> FL mě nepustí
b) zaplatím zboží A -> FL mě na stránku vpustí
c) majitel obsahu vytvoří  opravný daňový doklad na zboží A -> FL mě na stránku nevpustí (není platba k obsahu)

2. scénář - pro zobrazení stránky je vyžadováno zboží B
a) koupím si zboží A i B -> FL mě nepustí
b) zaplatím zboží A i B (jedna faktura) -> FL mě na stránku vpustí
c) majitel obsahu vytvoří  opravný daňový doklad na zboží B -> FL mě na stránku nevpustí (není platba k obsahu)

3. scénář - pro zobrazení stránky je vyžadováno zboží B
a) koupím si zboží A i B -> FL mě nepustí
b) zaplatím zboží A i B (jedna faktura) -> FL mě na stránku vpustí
c) majitel obsahu vytvoří  opravný daňový doklad na zboží A -> FL mě na stránku vpustí - zboží B z původní zaplacené faktury nefiguruje na opravném daňovém dokladu

4. scénář je vyžadováno zboží A nebo B
a) koupím si zboží A i B -> FL mě nepustí
b) zaplatím zboží A i B (jedna faktura) -> FL mě na stránku vpustí
c) majitel obsahu vytvoří  opravný daňový doklad na zboží A -> FL mě na stránku vpustí - zboží B z původní zaplacené faktury nefiguruje na opravném daňovém dokladu
d) majitel obsahu smaže ODD a udělá nový (nemůže vytvořit dva k jedné faktuře), na kterém figurují opravené položky A i B -> FL mě na stránku nevpustí
e) znovu zakoupím položku A + zaplatím položku A -> jsem vpuštěn na obsah
d) majitel obsahu vytvoří  ODD na zboží A -> FL mě na stránku nevpustí -> opět nemám obsah zaplacen

Celkem jsem to protestoval a ošetřil to tak ,aby všechny tyto možné scénáře fungovaly správně. K vyzkoušení na http://locker.happypaws.cz/

**Comment by radimtopic** [comment]
@kotmic Super! Díky, že sis dal práci s ošetřením všech těch stavů. 👍 

Teď už to bude snad opravdu jen kosmetika...

- [ ] Když skryju tlačítko pro zakoupení přístupu (přepínač "Zobrazit tlačítko pro zakoupení přístupu") příslušné nastavení v úpravě stránky se skryje, ale při příštím otevření nastavení stránky je opět vidět, přestože přepínač není v aktivním stavu.

![FL_tlačítko](https://user-images.githubusercontent.com/10176552/76299246-09244600-62bb-11ea-85b6-4057af268f90.png)


- [ ] Odkaz "Nastavení vzhledu FAPI Lockeru" (v nastavení zamčené stránky) obsahuje dvě lomítka v URL:
http://locker.happypaws.cz/wp-admin//options-general.php?page=fapi-locker
- [ ] Změnit text odkazu: "Nastavení vzhledu FAPI Lockeru" -> ""Nastavení FAPI Lockeru"
- [ ] Když na stránce zobrazím prodejní formulář (tlačítkem pro zakoupení přístupu), je mezi úvodním textem (zobrazeným před odemčením stránky) a prodejním formulářem zbytečně hodně prostoru. Nešlo by to odsazení zmenšit, popř. při zobrazení prodejního formuláře nezobrazovat ten úvodní text?

![locker_formulář](https://user-images.githubusercontent.com/10176552/76293948-47693780-62b2-11ea-98ea-87beb39aa373.png)

Jinak se mi moc nelíbí ty chybové hlášky. Je z nich hrozně cítit "programátorský" přístup - snaha jasně specifikovat všechny možné situace. Pro uživatele tam ale ty kódy chyb podle mě nemají co dělat (při ladění nebo testování se to hodí, ale běžnému uživateli to nic neřekne). To nejmenší, co s tím můžeme udělat, je aspoň z hlášek odstranit chybové kódy.

V souborech toho pluginu (konkrétně readme.md) jsem našel znění všech hlášek. Jestli jsou aktuální, tak bych minimálně změnil výchozí chybovou hlášku ("Tento obsah prozatím nemáte zakoupený! (kód 100)" -> "K tomuto obsahu nemáte přístup.") a možná by stály za zjednodušení i ty další hlášky. Pokud všechno funguje správně, tak je podle mě zbytečné v hlášce uživateli podprahově sdělovat, že na zadanou e-mailovou adresu sice ve FAPI evidujeme nějaké objednávky, ale není v nich obsažen produkt, který uděluje přístup k zamčené stránce. Zpráva pro uživatele by měla spočívat jen ve sdělení, že k danému obsahu nemá přístup. (Podobně jako u chybného zadání přístupových údajů systém obvykle nehlásí: Uživatelské jméno máte správně, ale v heslu jsou tři znaky špatně. ;-)

**Comment by slischka** [comment]
Pokud se jedná o hlášky v administraci. Potom bych tam klidně nechal chybové kód. Pokud s klientem budeme řešit že se nedá připojit k FAPI podle cyhbového kód by jsme byli schopní zjitit kde je přesně co špatně.

Pokud se ale jedná o chybové hlášky, které vídí pouze koncový klient. Potom jsem pro to napsat tak aby tam chybové kódy nebyly vůbec. 

Tohle se ale může upravovat v čase. Už jeden klient hlásil že FL vůbec nefunguje a dokonco rozbíjí další části webu takže bych, pokud už FL funkční verzi vydal, a postupně doupravil hlášky.

**Comment by radimtopic** [comment]
1) Ke službě FAPI se nelze připojit (kód 001). \nChybí přihlašovací údaje do FAPI.
2) Ke službě FAPI se nelze připojit (kód 001). \nNeplatné přihlašovací údaje do FAPI."
3) Ke službě FAPI se nelze připojit (kód 001).

- [ ] všechny 3 hlášky nahradit jednou univerzální hláškou: **Ke službě FAPI se nelze připojit.**
(Ať se tam ale určitě nezobrazuje "Invalid username" - viz screenshot.)

![FL01](https://user-images.githubusercontent.com/10176552/76382192-2ce99980-6358-11ea-8550-91d87019899c.png)


4) V nastavení FAPI LOCKER chybí název položky faktury (kód 101).

- Prodejní položku v nastavení stránky nejde nevybrat, tak nevím, kdy a kde se to má objevovat. (Možná na začátku, než se nějaká první položka nastaví?) Navíc je tam řeč o "nastavení FAPI LOCKER", kde se položka faktury vůbec nenastavuje. (???)

5) V nastavení FAPI LOCKER chybí jméno uživatele pro komunikaci s FAPI (kód 102).
6) V nastavení FAPI LOCKER chybí heslo pro komunikaci s FAPI (kód 103).

- Žádnou z těch hlášek se mi nepodařilo vyvolat. Vyskytují se tam ještě vůbec? Není to nějaký pozůstatek před tím, než se to předělalo? (V nastavení FL se při zadání chybných přístupových údajů objevuje obecná hláška: "Nepodařilo se připojit k FAPI. Zkontrolujte prosím své přihlašovací údaje.", což je v pořádku.)

7) Pro e-mailovou adresu priklad@priklad.cz neevidujeme žádnou objednávku ani platbu (kód 003 - neznámý e-mail). \nJe emailová adresa správná?
8) Pro e-mailovou adresu priklad@priklad.cz neregistrujeme žádnou objednávku ani platbu (kód 004 - žádné doklady). \nJe emailová adresa správná?
9) Pro e-mailovou adresu priklad@priklad.cz se nepodařilo nalézt platbu za tento obsah (kód 005).'

- [ ] všechny 3 hlášky nahradit jednou univerzální hláškou: **Pro e-mailovou adresu ... nebyla nalezena platba za tento obsah.**

10) Tento obsah prozatím nemáte zakoupený (kód 100). \nPro přístup je nutné obsah odemknout pomocí oprávněné e-mailové adresy nebo zakoupit.

- Nevím, kde se tahle hláška zobrazuje (jestli vůbec). Není to výchozí text zobrazovaný před odemčením stránky?

11) Připojení na FAPI není funkční. Nejprve je potřeba nastavit spojení na FAPI. (zamykaci stranka kdyz neni nastavene v Nastaveni->FAPI Locker)

- [ ] (hláška v nastavení zamčené stránky, když není nastaveno propojení s FAPI) nahradit hláškou: **Propojení s FAPI není funkční.**

**Comment by kotmic** [comment]
@radimtopic změny nasazeny, hodil jsem aktuální verzi do Githubu a taky to poslal na review na wordpress.com, kde pokud se zadaří, bude plugin uveden v katalogu pluginů: https://wordpress.org/plugins/ na adrese https://wordpress.org/plugins/fapi-locker (a na to se pak můžeme odkazovat..)

**Comment by kotmic** [comment]
Jinak ten review může trvat až sedm dní, tak pokud to bude ok, můžeme ten zip nahrát na ten náš web a zatím odkazovat jen na ně https://fapi.cz/fapi-locker/

zip je přiložen
[fapi-locker.zip](https://github.com/fapi-cz/fapi-locker/files/4332810/fapi-locker.zip)

**Comment by radimtopic** [comment]
Super, všechno zdá se funguje, jak má. 👍 

Ještě poslední 2 kosmetické věci...

- [ ] Změnit hlášku v nastavení FAPI Lockeru:
Stav propojení: připojeno -> Připojeno k FAPI.
(v nepřipojeném stavu se tam uvozující text "Stav propojení" nezobrazuje, tak ať je to konzistentní)
- [ ] Dalo by se odstranit to stínování z okrajů rámečku, ve kterém se celý FAPI Locker zobrazuje? Nevypadá to moc dobře a myslím si, že to ani není moc univerzálně slučitelné s vzhledem jiných stránek. (Viz obrázky. Myslím, že bez stínu to vypadá líp.)

![FL_shadow](https://user-images.githubusercontent.com/10176552/77182399-fbe23500-6acc-11ea-96ce-a29497c51baa.png)

![FL_no shadow](https://user-images.githubusercontent.com/10176552/77182425-043a7000-6acd-11ea-85b4-650cc849a5df.png)

**Comment by kotmic** [comment]
Obojí jsem upravil, finální soubor přikládám.
[fapi-locker.zip](https://github.com/fapi-cz/fapi-locker/files/4370027/fapi-locker.zip)

Je vytvořený z větve v3.0 a aktuálních zdrojáků.

Testoval jsem upgrade ze starší verze FL (2.2 a 2.4) a **výrazně to nedoporučuji**.

Z verze 2.4 se to povedlo, sice to napsalo nějakou chybu po přesměrování na Přehled pluginů, ale ta se už znovu nezobrazila. Bylo to něco kolem té starší verze a neschopnosti přehrát soubory. Ale nová verze se nahrála a fungovala..

Z verze 2.2 se to rozbilo uplně. Nešlo se po instalaci nové verze 3.0 do WP přihlásit a psalo to nějakou neznámou chybu. Tedy rozhodně nejčistší postup pro uživatele je:

- zazálohovat nastavení aktuálního FL, pokud někdo používá a funguje mu
- deaktivovat starou verzi FL
- odstranit starou verzi FL (zde může vzniknout problém, pokud někdo má verzi 2.2, nejde odstranit přes GUI a musí se odstranit přes FTP)
- nainstalovat novou verzi
- s největší pravděpodobností nastavení zůstanou a přenesou se "tak jak byly u staré verze".
- aktivovat novou verzi FL

**Comment by radimtopic** [comment]
@kotmic Díky za dotažení a otestování. Už jsem podle nové verze upravil i nápovědu: https://napoveda.fapi.cz/article/125-fapi-locker

Myslel jsem, že už to uzavřeme, ale ještě jsem znovu narazil na "Invalid username" v chybové hlášce (když jsem měl v propojení FL s FAPI vyplněno chybné uživatelské jméno "radim@fapi"). :-( Ať se tam při všech chybách propojení zobrazuje jen jedna univerzální hláška: **Ke službě FAPI se nelze připojit.**

![FL_invalid username](https://user-images.githubusercontent.com/10176552/77391833-008f3d80-6d9a-11ea-9164-9995fc7c3386.png)

Když už do toho budeš sahat, můžeš prosím ještě ošetřit tyhle kosmetické drobnosti?:

- [ ] Stín odstranit i z rámečku, který se zobrazuje okolo výzvy k zadání e-mailové adresy.

![FL_shadow2](https://user-images.githubusercontent.com/10176552/77391983-464c0600-6d9a-11ea-80ed-e2f41785b6db.png)

![FL_no shadow2](https://user-images.githubusercontent.com/10176552/77391992-4b10ba00-6d9a-11ea-94e6-d5b6ab741ed8.png)

- [ ] Doplnit tečku za větami "Připojeno k FAPI." (informace o stavu v nastavení pluginu) a "Zamykání stránek a článků s možností zakoupení přístupu přes prodejní aplikaci FAPI." (popis v anotaci pluginu)

**Comment by kotmic** [comment]
Opraveno. Za to "Invalid username." omluva, zůstalo to tam staticky jako vkládaná chyba z backendu wordpressu a nevšiml jsem si toho, nebyla to cíleně vložená hláška.

![image](https://user-images.githubusercontent.com/17206406/77405406-70f68880-6db3-11ea-86bf-c63843ada2f0.png)

Ostatní taky. Bylo to na 15 minut, takže pohoda. Nový zip příkládám..
[fapi-locker.zip](https://github.com/fapi-cz/fapi-locker/files/4374309/fapi-locker.zip)

**Comment by kotmic** [comment]
Úprava verze 3.0.0 -> 3.0
[fapi-locker.zip](https://github.com/fapi-cz/fapi-locker/files/4375933/fapi-locker.zip)

**Comment by kotmic** [comment]
@radimtopic 
Zapracované [připomínky od Šárky](https://trello.com/c/6ioCxTWx/216-fapi-locker), pokud už je zip na webu, vyměň ho prosím..
[fapi-locker.zip](https://github.com/fapi-cz/fapi-locker/files/4396829/fapi-locker.zip)

Díky

**Comment by radimtopic** [comment]
@kotmic Opravený soubor jsem dal do nápovědy: https://napoveda.fapi.cz/article/125-fapi-locker

Díky a omlouvám se za svou chybu.

**Comment by kotmic** [comment]
Tob byla spíš moje :-D Měl jsem to zkontrolovat..
